<?php include './Header.PHP';?>
<div class="container-fluid">
        <div class="row">
            <div class="col-12 d-flex justify-content-center align-content-center">
                <h1>Muralhas da China</h1>
            </div>

            <div class="row">
                <div class="col-3">
                    <div class="card">
                        <img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdx5v660Gq6lNu_j26C8TuVQataFRUn_QvjQ&s" alt="" style = 'width 100%'>
                    </div>
                </div>

                <div class="col-3">
                    <div class="card">
                        <img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdx5v660Gq6lNu_j26C8TuVQataFRUn_QvjQ&s" alt="" style = 'width 100%'>
                    </div>
                </div>

                <div class="col-3">
                    <div class="card">
                        <img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdx5v660Gq6lNu_j26C8TuVQataFRUn_QvjQ&s" alt="" style = 'width 100%'>
                    </div>
                </div>

                <div class="col-3">
                    <div class="card">
                        <img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdx5v660Gq6lNu_j26C8TuVQataFRUn_QvjQ&s" alt="" style = 'width 100%'>
                    </div>
                </div>

                <div class="col-3">
                    <div class="card">
                        <img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdx5v660Gq6lNu_j26C8TuVQataFRUn_QvjQ&s" alt="" style = 'width 100%'>
                    </div>
                </div>

                <div class="col-3">
                    <div class="card">
                        <img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdx5v660Gq6lNu_j26C8TuVQataFRUn_QvjQ&s" alt="" style = 'width 100%'>
                    </div>
                </div>

                <div class="col-3">
                    <div class="card">
                        <img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdx5v660Gq6lNu_j26C8TuVQataFRUn_QvjQ&s" alt="" style = 'width 100%'>
                    </div>
                </div>
                
                <div class="col-3">
                    <div class="card">
                        <img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdx5v660Gq6lNu_j26C8TuVQataFRUn_QvjQ&s" alt="" style = 'width 100%'>
                    </div>
                </div>

                <div class="col-3">
                    <div class="card">
                        <img  src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdx5v660Gq6lNu_j26C8TuVQataFRUn_QvjQ&s" alt="" style = 'width 100%'>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php include './Footer.PHP';?>